### PR TITLE
files for pip install

### PR DESCRIPTION
**Pull request by jamesmkrieger**
Here are some first draft files that make pip install work, which enables easier imports.

Please feel free to change them as I'm sure I made some mistakes based on limited information

### CODE REVIEW

**Comment by jamesmkrieger** [comment]
Please note: this only installs opusDSD itself and assumes that the dependencies have already been installed in the conda environment

**Comment by jamesmkrieger** [comment]
It means that we can run the scripts from outside the directory that they are in, which is really helpful

**Comment by alncat** [comment]
Looks great!

**Comment by alncat** [comment]
> It means that we can run the scripts from outside the directory that they are in, which is really helpful

James, thanks for this! I now added an entry point in setup.py. We can run dsd using command like ```dsd commandx``` now.

**Pull request merged**
